### ISSUE TITLE
AssembleEx can't handle RETN instructions

### ISSUE THREAD

**Issue by wangray** [x64dbg/x64dbgpy#20]
I get the error

```
<b>Traceback (most recent call last):</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\mona.py", line 18092, in main</b>
<b>    commands[command].parseProc(opts)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\mona.py", line 11571, in procROP</b>
<b>    findROPGADGETS(modulecriteria,criteria,endings,maxoffset,depth,split,thedistance,fast,mode)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\mona.py", line 6305, in findROPGADGETS</b>
<b>    found_opcodes = searchInModule(search,thismodule,criteria)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\mona.py", line 5284, in searchInModule</b>
<b>    return searchInRange(sequences, start, end, criteria)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\mona.py", line 5206, in searchInRange</b>
<b>    buf = dbg.assemble(seq)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\x64dbgpylib.py", line 1285, in assemble</b>
<b>    res = script.assembler.AssembleEx(address, line)</b>
<b>  File "Z:\raywang\SNAP~E08\release\x32\plugins\x64dbgpy\x64dbgpy\pluginsdk\_scriptapi\assembler.py", line 20, in AssembleEx</b>
<b>    raise Exception(error.value)</b>
<b>Exception: invalid instruction</b>
```
 
on a `RETN` instruction.

**Comment by mrexodia** [comment]
This is due to asmtk not supporting the `retn` instruction. I made a small note [here](https://github.com/x64dbg/x64dbg/projects/2#card-5030998), but basically my workaround would be to replace `retn` with `ret`

**Comment by wangray** [comment]
Ok, I'll do that.
